version: '3'

services:
  postgres:
    container_name: postgres14
    image: 'postgres:14.2'
    ports:
      - "5434:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: technical-test
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/